# Generated by Django 3.1.4 on 2020-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Object datetime when someone.'),
        ),
    ]
