# Generated by Django 3.1.4 on 2020-12-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201204_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'get_latest_by': 'joined', 'ordering': ['-joined']},
        ),
        migrations.AddField(
            model_name='group',
            name='pic',
            field=models.TextField(null=True),
        ),
    ]
