# Generated by Django 3.1.4 on 2020-12-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20201205_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='picture',
        ),
    ]
